version: '2'
services:
  ### Mysql Container
  mysql:
    container_name: "Mysql_netapi"
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: todo
      - MYSQL_USER: root
      - MYSQL_PASSWORD: root
      - MYSQL_ROOT_HOST: "%"
